apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-githubreleasesmonitor-editor-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cve-operator.csye7125.me
  resources:
  - githubreleasesmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cve-operator.csye7125.me
  resources:
  - githubreleasesmonitors/status
  verbs:
  - get