apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-githubrelease-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cve-operator.csye7125.me
  resources:
  - githubreleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cve-operator.csye7125.me
  resources:
  - githubreleases/status
  verbs:
  - get